// This file is autogenerated by liwe3-svelte
/* eslint-disable @typescript-eslint/no-explicit-any */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

/** CommentType */
export interface CommentType {
	/** Unique comment identifier */
	id: string;
	/** Domain identifier */
	domain: string;
	/** Module identifier */
	module: string;
	/** Object identifier */
	id_obj: string;
	/** User identifier */
	id_user: string;
	/** Comment visibility */
	visible: boolean;
	/** Comment text content */
	text: string;
}

